services:
  mariadb:
    image: mariadb:11.2
    restart: always
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_DOCKER_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - qualitylab-net

  quality-lab-pro:
    restart: always
    image: leonardomeireles55/quality-lab-pro-back-end:latest
    working_dir: /usr/src/app
    container_name: quality-lab-pro
    ports:
      - ${SERVER_LOCAL_PORT}:${SERVER_DOCKER_PORT}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVER_PORT: ${SERVER_DOCKER_PORT}
      API_SECURITY_TOKEN_SECRET: ${API_SECURITY_TOKEN_SECRET}
      API_SECURITY_ISSUER: ${API_SECURITY_ISSUER}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      EMAIL_TO_SEND_LIST: ${EMAIL_TO_SEND_LIST}
    command: [ "java", "-jar", "-Dspring.profiles.active=prod", "app.jar" ]
    networks:
      - qualitylab-net

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx:/etc/nginx:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    networks:
      - qualitylab-net
    ports:
      - '80:80'
      - '443:443'
networks:
  qualitylab-net:
    external: true
volumes:
  mysql-volume:
