version: '3.8'
services:
  mariadb:
    image: mariadb:10.10
    restart: always
    env_file: ./.env
    environment:
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
    ports:
      - "8082:8082"
#      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
  docker-app:
    restart: on-failure
    depends_on:
      - mariadb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: qualityLabPro
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mariadb:${MYSQLDB_DOCKER_PORT}/${MYSQLDB_DATABASE}
      - SPRING_DATASOURCE_USERNAME=$MYSQLDB_USER
      - SPRING_DATASOURCE_PASSWORD=$MYSQLDB_ROOT_PASSWORD
    stdin_open: true
    tty: true
volumes:
    mysql-volume: