services:
  mariadb:
    image: mariadb:10.10
    restart: always
    env_file: ./.env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  quality-lab-pro:
    restart: on-failure
    build:
      context: ./ 
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: quality-lab-pro
    env_file: ./.env
    ports:
      - ${SERVER_LOCAL_PORT}:${SERVER_DOCKER_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
  nginx:
    restart: always
    image: nginx
    hostname: quality-lab-pro:8080
    volumes:
      - ./nginx:/etc/nginx:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    ports:
      - 80:80
      - 443:443
    depends_on:
      - quality-lab-pro
volumes:
  mysql-volume:
