services:
  mariadb:
    image: mariadb:11.2
    restart: always
    env_file: ./.env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - app-network

  quality-lab-pro:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: quality-lab-pro
    env_file: ./.env
    ports:
      - ${SERVER_LOCAL_PORT}:${SERVER_DOCKER_PORT}
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
      SERVER_PORT: ${SERVER_DOCKER_PORT}
      API_SECURITY_TOKEN_SECRET: ${API_SECURITY_TOKEN_SECRET}
      API_SECURITY_ISSUER: ${API_SECURITY_ISSUER}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      EMAIL_TO_SEND_LIST: ${EMAIL_TO_SEND_LIST}
    command: [ "java", "-jar", "-Dspring.profiles.active=local", "app.jar" ]
    networks:
      - app-network

  nginx:
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx/dev:/etc/nginx:ro
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network

volumes:
  mysql-volume:

networks:
  app-network:
    driver: bridge
