version: '3.8'
services:
  mariadb:
    image: mariadb:10.10
    restart: always
    env_file: ./.env
    environment:
      DB_DATABASE: ${DB_DATABASE}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
  docker-app:
    restart: on-failure
    depends_on:
      - mariadb
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: quality-lab-pro
    env_file: ./.env
    ports:
      - ${SERVER_LOCAL_PORT}:${SERVER_DOCKER_PORT}
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_ROOT_PASSWORD}
    stdin_open: true
    tty: true
    expose:
      - 80
volumes:
  mysql-volume:
