services:
  mariadb:
    image: mariadb:11.2

  quality-lab-pro:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    image: leonardomeireles55/quality-lab-pro-back-end:latest

  nginx:
    restart: always
    image: nginx:latest