services:
  mariadb:
    image: mariadb:10.10
    restart: always
    env_file: ./.env
    environment:
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d

  certbot:
    image: certbot/certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /tmp/letsencrypt:/tmp/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $!; certbot renew; done;'"

  docker-app:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    container_name: quality-lab-pro
    env_file: ./.env
    ports:
      - ${SERVER_LOCAL_PORT}:${SERVER_DOCKER_PORT}
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - docker-app
      - certbot

volumes:
  mysql-volume: