FROM eclipse-temurin:21-jdk-alpine

RUN apk add --no-cache maven

WORKDIR /usr/src/app

ENV SERVER_PORT=8080 \
    SPRING_PROFILES_ACTIVE=dev

EXPOSE ${SERVER_PORT}

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
