ALTER TABLE generic_analytics
ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
ADD COLUMN user_id BIGINT,
ADD CONSTRAINT fk_generic_analytics_user 
    FOREIGN KEY (user_id) 
    REFERENCES users(id);